import './components/lenis-scroll.js'
import './components/navbar.js'
import './components/sticky-text.js'
import './components/tabs.js'
import './components/reviews.js'
import './components/stats.js'
import './components/faqs.js'
